name: Automatisation

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher Message
        run: echo "Une modification a été push dans la branche main"